version: "3.1"
services:
  redis:
    restart: always
    image: redis
    container_name: redis
    tty: true
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: gateway
