set nu
set cursorline
set nobackup
set nowritebackup
set hlsearch
set fileencodings=ucs-bom,utf-8,chinese,default,latin1
set ruler
set ignorecase
set incsearch
set showcmd
set laststatus=2
set scrolloff=3
