version: "3.1"
services:
  redis:
    restart: always
    image: redislabs/redisinsight
    container_name: redisinsight
    tty: true
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8001:8001

networks:
  default:
    external:
      name: gateway
