version: "3.1"
services:
  mongo:
    restart: always
    image: mongo
    container_name: mongo
    ports:
     - 27017:27017
    tty: true
    environment:
      TZ: Asia/Shanghai
      
networks:
  default:
    external:
      name: gateway
    

