version: "3.1"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    container_name: kafdrop
    ports:
      - 9100:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092"

networks:
  default:
    external:
      name: gateway
