version: "3.1"
services:
  mysql:
    restart: always
    # image: mysql:8.0.16
    image: mysql:5.7
    container_name: mysql
    tty: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.conf:/var/lib/mysql-files/my.conf
    command:
      - mysqld
      - --defaults-file=/var/lib/mysql-files/my.conf
networks:
  default:
    external:
      name: gateway
