version: '3'
services:
  svn:
    restart: always
    image: garethflowers/svn-server:latest
    container_name: svn
    privileged: true
    ports:
      - '3690:3690'
    volumes:
      - ./data:/var/opt/svn
