version: '2'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager            
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "admin"
    ports:
      - "39000:9000"


networks:
  default:
    external:
      name: gateway
